services:
  - name: inventory-service
    image: mini-orchestrator-inventory-service:latest
    replicas: 3
    containerPort: 8080
    healthPath: /health
    env: {}

  - name: orders-service
    image: mini-orchestrator-orders-service:latest
    replicas: 1
    containerPort: 8080
    hostPort: 8090
    healthPath: /health
    env:
      INVENTORY_SERVICE_URL: http://inventory-service:8080
